name: Upload to FTP
on:
  push:
    branches: [ main ]
jobs:
  upload:
    name: Upload ğŸ”¼
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code ğŸ‘€
        uses: actions/checkout@v2

      - name: Sync files ğŸ“
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server-dir: Cook-Off_1.0/
          server:  198.50.253.148
          username:  Calverin.9196
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: .git/**
            - node_modules/**
            - *.dat
            - *.dat_old
            - region/**
            - data/**
            - DIM1/**
            - DIM-1/**
            - entities/**
            - playerdata/**
            - poi/**
            - session.lock

      - name: RCON Connection ğŸ”Œ
        uses: Plagiatus/RCON-Action@v0.1
        with:
          server: 198.50.253.148
          password: ${{ secrets.RCON_PASSWORD }}
          commands: '["reload", "say You just got RCONned B)"]'